name: Windows build for x86-64

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install Cross
              shell: bash
              run: |
                  curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
                  cargo binstall --no-confirm cross

            - name: Build binary
              run: cross build --release --verbose --target x86_64-pc-windows-gnu

            - name: Run tests
              run: cargo test --verbose

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: discord-always-typing.exe
                  path: target/x86_64-pc-windows-gnu/release/discord-always-typing.exe
